### ISSUE TITLE
CI does not run `go test` or the frontend test suite

### ISSUE THREAD

**Issue by CodeBuildder** [spiffe/tornjak#748]
\`.github/workflows/ci.yaml\` currently only runs \`golangci-lint\`, \`make binaries\`, and \`make images\`. It never runs \`go test ./...\` or the frontend Jest/Enzyme suite (\`npm test\` in \`frontend/\`), so a PR that breaks either test suite can still pass CI and get merged.

This isn't hypothetical - the frontend suite appears to have been broken on \`main\` since PR #231 (merged 2023-05-24): \`cluster-list.test.jsx\` and \`cluster-create.test.jsx\` both import \`@wojtekmaj/enzyme-adapter-react-17\`, but it was never added to \`frontend/package.json\`. A clean \`npm install && npm test\` fails immediately with \`Cannot find module '@wojtekmaj/enzyme-adapter-react-17'\`. It's gone unnoticed for ~3 years, presumably because nothing in CI ever runs the suite. Separately, once that's installed, \`cluster-create.test.jsx\`'s snapshot no longer matches the component's current rendered output.

Proposed fix:
- Add a \`go test ./...\` step to \`ci.yaml\`
- Add an \`npm test\` step (CI mode, e.g. \`CI=true npx react-scripts test -env=jsdom --watchAll=false\`) for \`frontend/\`
- Fix the currently-broken frontend suite (missing dependency + stale snapshot) so the new step actually passes rather than immediately going red

Happy to send a PR for this.

**Comment by CodeBuildder** [comment]
Duplicate - accidentally created twice while the first attempt was failing on assignee permissions. Continuing in #749.
